import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,tick,build,upgrade,repair,travel,serialize,deserialize,maxHull,capacity,startBattle,fire,ability,leaveBattle,FACTIONS,distance} from '../src/simulation.js';
const advance=(s,t,input)=>{for(let i=0;i<Math.ceil(t*10);i++)tick(s,.1,input);};
function battle(f='kaiju',enemy='crawler'){const s=createGame(f);s.enemies[0].faction=enemy;s.x=s.enemies[0].x-25;s.z=s.enemies[0].z;assert.ok(startBattle(s,'rival1'));s.battle.autoFire=false;return s;}
test('all city types start with distinct balanced roles',()=>{for(const f of Object.keys(FACTIONS)){const s=createGame(f);assert.equal(s.hp,maxHull(s));assert.equal(s.buildings.filter(Boolean).length,3);assert.equal(capacity(s),30);}assert.ok(FACTIONS.kaiju.melee>FACTIONS.crawler.melee);assert.ok(FACTIONS.airship.range>FACTIONS.crawler.range);assert.ok(FACTIONS.crawler.hp>FACTIONS.kaiju.hp);});
test('building spends exactly once and finishes after its duration',()=>{const s=createGame();assert.ok(build(s,'sawmill',0).ok);assert.equal(s.resources.wood,135);assert.equal(s.resources.iron,115);assert.equal(build(s,'sawmill',0).ok,false);advance(s,8);assert.equal(s.buildings[0].remaining,0);assert.equal(s.stats.built,1);});
test('invalid placements and unaffordable orders never spend resources',()=>{const s=createGame();const before={...s.resources};for(const slot of [-1,20,.5,7])assert.equal(build(s,'housing',slot).ok,false);assert.deepEqual(s.resources,before);s.resources.wood=0;assert.equal(build(s,'housing',0).ok,false);assert.equal(s.buildings[0],null);});
test('district upgrades are delayed, capped at three, and armour improves hull',()=>{const s=createGame();s.resources={wood:1000,iron:1000,food:1000};assert.ok(build(s,'armor',0).ok);advance(s,9);assert.equal(maxHull(s),660);assert.equal(s.hp,660);assert.ok(upgrade(s,0).ok);assert.equal(s.buildings[0].level,1);advance(s,9);assert.equal(s.buildings[0].level,2);assert.equal(maxHull(s),780);assert.ok(upgrade(s,0).ok);advance(s,9);assert.equal(s.buildings[0].level,3);assert.equal(upgrade(s,0).ok,false);});
test('travel arrives and gathers finite deposits while stopped',()=>{const s=createGame();const n=s.nodes[0];n.amount=20;travel(s,n.x,n.z);advance(s,12);assert.ok(distance(s,n)<.2);assert.equal(s.target,null);advance(s,20);assert.equal(n.amount,0);assert.equal(s.stats.gathered,20);assert.equal(s.resources.wood,180);});
test('timber guild doubles gathering and movement stops gathering',()=>{const a=createGame(),b=createGame();for(const s of [a,b]){s.x=s.nodes[0].x;s.z=s.nodes[0].z;}b.buildings[0]={type:'sawmill',level:1,remaining:0};advance(a,5);advance(b,5);assert.ok(Math.abs((b.resources.wood-160)-2*(a.resources.wood-160))<.001);const old=b.resources.wood;advance(b,1,{x:1,z:0});assert.equal(b.resources.wood,old);});
test('food consumption and housing capacity form an economy',()=>{const s=createGame();s.buildings[13]=null;s.resources.food=0;advance(s,12);assert.ok(s.population<24);assert.equal(s.resources.food,0);s.resources.food=100;s.buildings[1]={type:'housing',level:2,remaining:0};assert.equal(capacity(s),54);const p=s.population;advance(s,12);assert.ok(s.population>p);});
test('pause freezes simulation; diagonal travel has normalized speed',()=>{const s=createGame(),before=serialize(s);s.paused=true;advance(s,15);s.paused=false;assert.equal(serialize(s),before);const a=createGame(),b=createGame();const ax=a.x,az=a.z;advance(a,1,{x:1,z:0});advance(b,1,{x:1,z:1});assert.ok(Math.abs(distance(a,{x:ax,z:az})-distance(b,{x:ax,z:az}))<.0001);});
test('battles require proximity; retreat returns to management at a cost',()=>{const s=createGame();assert.equal(startBattle(s,'rival1'),false);s.x=s.enemies[0].x;s.z=s.enemies[0].z;assert.ok(startBattle(s,'rival1'));assert.equal(build(s,'housing',0).ok,false);const food=s.resources.food;assert.ok(leaveBattle(s,true));assert.equal(s.mode,'expedition');assert.equal(s.resources.food,food-20);});
test('weapons respect range and reload, and kaiju strikes harder within physical reach',()=>{const s=battle();assert.equal(fire(s),false);s.battle.player.x=0;s.battle.enemy.x=45;const hp=s.battle.enemyHp;assert.ok(fire(s));assert.equal(s.battle.enemyHp,hp);advance(s,.6);assert.equal(hp-s.battle.enemyHp,FACTIONS.kaiju.damage);assert.equal(fire(s),false);s.battle.reload=0;s.battle.enemy.x=20;const rangedHp=s.battle.enemyHp;assert.ok(fire(s));advance(s,.6);assert.equal(rangedHp-s.battle.enemyHp,FACTIONS.kaiju.damage);s.battle.reload=0;s.battle.enemy.x=17;const before=s.battle.enemyHp;assert.ok(fire(s));advance(s,.7);assert.equal(before-s.battle.enemyHp,FACTIONS.kaiju.melee);});
test('rush closes the gap, damages at contact, and starts cooldown',()=>{const s=battle();s.battle.player.x=0;s.battle.enemy.x=60;const hp=s.battle.enemyHp;assert.ok(ability(s).ok);assert.ok(distance(s.battle.player,s.battle.enemy)<=22.1);assert.equal(s.battle.enemyHp,hp);advance(s,.7);assert.equal(s.battle.enemyHp,hp-85);assert.equal(ability(s).ok,false);});
test('airship AI kites while kaiju AI closes distance',()=>{const a=battle('crawler','airship');a.battle.player.x=0;a.battle.enemy.x=50;advance(a,1);assert.ok(distance(a.battle.player,a.battle.enemy)>50);const b=battle('crawler','kaiju');b.battle.player.x=0;b.battle.enemy.x=50;advance(b,1);assert.ok(distance(b.battle.player,b.battle.enemy)<50);});
test('victory grants loot exactly once at contact and defeat can be detected',()=>{const s=battle();s.battle.player.x=0;s.battle.enemy.x=20;s.battle.enemyHp=1;const old=s.resources.iron;assert.ok(fire(s));assert.equal(s.battle.result,null);assert.equal(s.resources.iron,old);advance(s,.6);assert.equal(s.battle.result,'victory');assert.equal(s.stats.victories,1);assert.equal(s.resources.iron,old+100);advance(s,10);assert.equal(s.resources.iron,old+100);assert.ok(leaveBattle(s));assert.equal(s.enemies[0].defeated,true);assert.equal(startBattle(s,'rival1'),false);const d=battle();d.hp=1;d.battle.player.x=0;d.battle.enemy.x=20;advance(d,4);assert.equal(d.battle.result,'defeat');assert.equal(d.hp,0);});

test('pending impacts survive pause and save, resolve once, and respect both speeds',()=>{for(const faction of ['kaiju','crawler','airship'])for(const speed of [1,2]){let s=battle(faction);s.battle.enemyReload=999;s.battle.player.x=0;s.battle.enemy.x=faction==='kaiju'?17:40;const hp=s.battle.enemyHp;assert.ok(fire(s));const hit=s.battle.pendingHits[0];tick(s,.2);assert.equal(s.battle.enemyHp,hp);s.paused=true;advance(s,2);assert.equal(s.battle.enemyHp,hp);s=deserialize(serialize(s));assert.ok(s);s.speed=speed;while(s.battle.time+.01*speed<hit.impactAt-1e-7){tick(s,.01);assert.equal(s.battle.enemyHp,hp);}tick(s,.01);assert.equal(s.battle.enemyHp,hp-hit.damage);assert.equal(s.battle.pendingHits.length,0);advance(s,.8);assert.equal(s.battle.enemyHp,hp-hit.damage);}});
test('legacy battle saves do not replay damage and corrupt pending hits are rejected',()=>{const s=battle();delete s.battle.pendingHits;assert.deepEqual(deserialize(serialize(s)).battle.pendingHits,[]);s.battle.pendingHits=[{eventId:1,source:'player',damage:-1,impactAt:1}];assert.equal(deserialize(serialize(s)),null);});
test('repair is paid, capped, and unavailable in battles',()=>{const s=createGame();assert.equal(repair(s).ok,false);s.hp=500;assert.ok(repair(s).ok);assert.equal(s.hp,540);assert.equal(s.resources.iron,115);const b=battle();b.hp=5;assert.equal(repair(b).ok,false);});
test('saves round-trip construction, travel, and battles, rejecting corrupt input',()=>{const s=createGame('airship');build(s,'cannon',0);travel(s,30,45);advance(s,2);const loaded=deserialize(serialize(s));assert.ok(loaded);assert.deepEqual(loaded,s);const b=battle();assert.ok(deserialize(serialize(b)).battle);assert.equal(deserialize('{oops'),null);assert.equal(deserialize('{"version":2}'),null);const bad=JSON.parse(serialize(s));bad.resources.wood=-2;assert.equal(deserialize(JSON.stringify(bad)),null);});
test('each faction can win the three-rival expedition with affordable preparation',()=>{for(const faction of Object.keys(FACTIONS)){const s=createGame(faction);assert.ok(build(s,'cannon',0).ok);assert.ok(build(s,'armor',1).ok);advance(s,10);for(const rival of s.enemies){s.x=rival.x-32;s.z=rival.z;assert.ok(startBattle(s,rival.id));s.battle.command=faction==='airship'?'retreat':'approach';for(let i=0;i<2200&&!s.battle.result;i++){tick(s,.1);if(s.battle.abilityCooldown<=0)ability(s);}assert.equal(s.battle.result,'victory',`${faction} against ${rival.faction}`);assert.ok(leaveBattle(s));while(s.hp<maxHull(s)&&s.resources.wood>=15&&s.resources.iron>=20)repair(s);}assert.equal(s.stats.victories,3);}});
