import {FACTIONS,BUILDINGS,SAVE_KEY,createGame,build,upgrade,upgradeCost,repair,travel,tick,distance,capacity,maxHull,income,startBattle,fire,ability,leaveBattle,serialize,deserialize,expandRing,slotUnlocked,setBatteryFacing,weaponStatus} from './simulation.js';
import {GameScene} from './scene.js';
import {RING_SLOTS,kaijuSlotPosition} from './city-layout.js';
import {facingOf,defaultFacing,batteryArc,normalizeAngle} from './weapon-layout.js';
import {terrainHeight,riverX} from './terrain.js';

const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=createGame(),started=false,view='city',selectedSlot=null,selectedBuilding=null,selection=null,scene,keys=new Set(),touch=new Set(),previous=performance.now(),uiElapsed=0,saveElapsed=0,toastTimer,resultShown=false,priorPause=false,uiSignature='',audioContext,audioEnabled=false,lastAudioEvent=0;
const markerEls=[];const mapContext=$('minimap').getContext('2d');
let cachedSave=null;try{cachedSave=deserialize(localStorage.getItem(SAVE_KEY));}catch{}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3800);}
function sound(freq=220,duration=.14,type='triangle'){if(!audioEnabled||!audioContext)return;const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,audioContext.currentTime);osc.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.35),audioContext.currentTime+duration);gain.gain.setValueAtTime(.045,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);osc.connect(gain);gain.connect(audioContext.destination);osc.start();osc.stop(audioContext.currentTime+duration);}
function save(show=false){if(!started)return;try{const raw=serialize(state);localStorage.setItem(SAVE_KEY,raw);cachedSave=deserialize(raw);if(show)toast('Expedition saved on this PC.');}catch{toast('Browser storage is unavailable. This expedition cannot be saved.');}}
function chooseFaction(faction){if(!FACTIONS[faction])return;state=createGame(faction);scene.setGame(state,{preview:true});scene.setView('city');selectedSlot=null;document.querySelectorAll('[data-faction]').forEach(b=>b.classList.toggle('active',b.dataset.faction===faction));const f=FACTIONS[faction];$('faction-description').innerHTML=`<span class="eyebrow">${f.tag}</span><h2>${f.subtitle}</h2><p>${f.description}</p>`;}
function markerSetup(){for(const el of markerEls)el.remove();markerEls.length=0;for(const n of [...state.nodes,...state.enemies]){const e=document.createElement('button');e.className='map-marker'+(n.faction?' rival':'');e.dataset.id=n.id;e.textContent=(n.faction?'◆ ':n.kind==='wood'?'♧ ':n.kind==='iron'?'⬡ ':'❧ ')+n.name;e.addEventListener('click',()=>select(n.faction?{enemy:n.id}:{node:n.id}));$('markers').append(e);markerEls.push(e);} $('destinations').replaceChildren();for(const n of state.nodes){const b=document.createElement('button');b.textContent=`${n.name} · ${n.kind}`;b.addEventListener('click',()=>{travelToResource(n);toast(`Course set for ${n.name}. Gathering starts on arrival.`);renderUI();});$('destinations').append(b);}}
function beginGame(saved=null){state=saved||createGame(state.faction);state.paused=false;started=true;view='city';selection=null;selectedSlot=null;selectedBuilding=null;uiSignature='';resultShown=false;lastAudioEvent=0;scene.setGame(state);scene.setView(view);$('intro').classList.add('hidden');$('faction-select').classList.add('hidden');$('hud').classList.remove('hidden');$('markers').classList.remove('hidden');markerSetup();renderUI();if(!saved)toast('Your expedition begins. Travel to the grove, or build your first district.');sound(130,.6);}
function changeView(v){if(state.mode==='battle'||v==='carrier'&&state.faction!=='kaiju')return;view=v;scene.setView(v);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderUI();}
function travelToResource(node){const d=distance(state,node);const dx=d>.01?(state.x-node.x)/d:0,dz=d>.01?(state.z-node.z)/d:1;travel(state,node.x+dx*22,node.z+dz*22);}
function actionResult(r){if(!r.ok)toast(r.message);else{sound(360);selectedBuilding=null;uiSignature='';renderUI();}return r.ok;}
function select(hit){if(!started||$('dialog').open)return;if(state.mode==='battle'){return;}
 if(hit.slot!==undefined){selectedSlot=hit.slot;selection={slot:hit.slot};if(selectedBuilding){actionResult(build(state,selectedBuilding,hit.slot));}renderUI();}
 else if(hit.node){selection={node:hit.node};selectedSlot=null;selectedBuilding=null;renderUI();}
 else if(hit.enemy){selection={enemy:hit.enemy};selectedSlot=null;selectedBuilding=null;renderUI();}
 else if(hit.ground){if(selectedBuilding){toast('Choose an empty district on the city deck, or use the district grid.');return;}travel(state,hit.ground.x,hit.ground.z);selection=null;selectedSlot=null;sound(290,.08);renderUI();}}
function showDialog(html){priorPause=state.paused;state.paused=true;keys.clear();touch.clear();$('dialog-content').innerHTML=html;$('dialog').showModal();renderUI();}
function closeDialog(){if($('dialog').open)$('dialog').close();}
$('dialog').addEventListener('close',()=>{if(!state.battle?.result)state.paused=priorPause;renderUI();});
$('close-dialog').addEventListener('click',closeDialog);
function showHelp(){showDialog(`<span class="eyebrow">FIELD MANUAL</span><h2>Make a moving home.</h2><p>Begin by building a Timber guild. Travel to the Sunken Grove using the world map or Resource destinations. Your crews gather automatically when your city stops nearby.</p><div class="help-grid"><b>W A S D / Arrows</b><span>Move your city in the camera’s direction.</span><b>Drag / Scroll</b><span>Orbit the camera / zoom in and out.</span><b>1 / 2 / 3 / 4</b><span>City / world / titan / streets. Streets brings you close to the people.</span><b>Castle rings</b><span>Add an outer ring to unlock plots, then upgrade districts upward.</span><b>Weapon placement</b><span>Select a battery to set its firing direction. Keep cannon lines clear of your buildings.</span><b>Build a district</b><span>Choose a building below, then click an empty city plot. You can also use the numbered district grid.</span><b>Upgrade</b><span>Select an existing building. Districts have three levels.</span><b>Battle</b><span>Move within 42 metres of a rival, select it, and engage. Use Approach or Keep distance. Guns fire automatically in range.</span><b>Space / E</b><span>Fire weapons / use your city’s special ability.</span><b>P</b><span>Pause. Building orders also work while paused.</span></div><p>Food feeds your population. Gardens produce food; woodland and ruins provide wood and iron. Falling to zero food slowly reduces population. Defeat all three rivals to secure the region. No rival attacks until you engage.</p><p>Progress autosaves every 30 seconds, plus when the game is hidden or closed. Sound is optional. Everything runs on this PC.</p><button class="primary" data-dialog-action="close">Back to the expedition</button>`);}
function menu(){showDialog(`<span class="eyebrow">EXPEDITION PAUSED</span><h2>A moment at anchor.</h2><p>Your city is safe while this menu is open.</p><div class="menu-buttons"><button class="primary" data-dialog-action="close">Resume expedition</button><button data-dialog-action="save">Save on this PC</button><button data-dialog-action="help">Controls & help</button><button data-dialog-action="title">Save & return to title</button></div>`);}
function returnToTitle(){save();closeDialog();started=false;state=createGame(state.faction);$('hud').classList.add('hidden');$('intro').classList.remove('hidden');$('faction-select').classList.remove('hidden');$('markers').classList.add('hidden');$('continue').classList.remove('hidden');document.body.classList.remove('in-battle');chooseFaction(state.faction);}
$('dialog-content').addEventListener('click',e=>{const a=e.target.closest('[data-dialog-action]')?.dataset.dialogAction;if(!a)return;if(a==='close')closeDialog();if(a==='save')save(true);if(a==='help'){closeDialog();showHelp();}if(a==='title')returnToTitle();if(a==='return'){leaveBattle(state);state.paused=false;resultShown=false;closeDialog();uiSignature='';renderUI();save();}if(a==='restart'){closeDialog();beginGame();}});
function showResult(){const b=state.battle;if(!b?.result||resultShown)return;resultShown=true;const victory=b.result==='victory',complete=state.stats.victories===3;showDialog(`<span class="eyebrow">${complete?'THE ASHEN REACH IS YOURS':victory?'BATTLE WON':'EXPEDITION LOST'}</span><h2>${complete?'A future worth carrying.':victory?'The city still stands.':'Even giants can fall.'}</h2><p>${complete?'All three rival cities have fallen. Your people have a place in this world. Keep building and exploring, or begin again with a different city.':victory?`You defeated ${esc(b.enemyName)}. Salvage crews are bringing supplies aboard. Repair your hull before the next engagement.`:'Your city was overwhelmed. Try building gun batteries and bulwarks, repair before battle, and fight at the distance that suits your city.'}</p>${victory?'<div class="result-loot"><span>+95 wood</span><span>+100 iron</span><span>+65 food</span></div>':''}<button class="primary" data-dialog-action="${victory?'return':'restart'}">${victory?'Return to the expedition':'Begin a new expedition'}</button>${!victory?'<button class="text-button" data-dialog-action="title">Return to city selection</button>':''}`);sound(victory?440:70,.8);save();}
function districtGrid(){
 const groups=state.faction==='kaiju'?RING_SLOTS:[Array.from({length:20},(_,i)=>i)];
 return `<div class="district-grid">${groups.map((slots,ring)=>`${state.faction==='kaiju'?`<span class="ring-label">${['Castle heart','Inner ward','Outer ward'][ring]}${ring>state.rings?' · Add a ring to unlock':''}</span>`:''}${slots.map(i=>{const b=state.buildings[i],locked=!slotUnlocked(state,i);return `<button data-slot="${i}" class="${b?'occupied':''} ${locked?'locked':''}" ${b||locked?'disabled':''} title="District ${i+1}${locked?' · Ring not built':b?' · Occupied':''}">${i+1}</button>`;}).join('')}`).join('')}</div>`;
}
function batteryControls(slot,b){
 const facing=facingOf(state.faction,slot,b),arc=Math.round(batteryArc(state.faction)*180/Math.PI);
 return `<div class="battery-placement"><div class="eyebrow">WEAPON DIRECTION · ${arc}° ARC</div><p>${state.faction==='airship'?'Missiles clear your buildings and turn through a wide arc.':'Cannon fire needs a clear line past your other buildings. Outer positions offer better coverage.'}</p><div class="bearing-controls">${[['Fore',0],['Starboard',Math.PI/2],['Aft',Math.PI],['Port',-Math.PI/2],['Face outward',defaultFacing(state.faction,slot)]].map(([label,a])=>`<button data-facing="${a}" data-aim-slot="${slot}" class="${Math.abs(normalizeAngle(facing-a))<.01?'active':''}">${label}</button>`).join('')}</div><small>Gold outline: firing arc · ${FACTIONS[state.faction].range} m range</small></div>`;
}
function renderSelection(){
 let html='';
 if(selectedBuilding){const b=BUILDINGS[selectedBuilding];html=`<div class="eyebrow">PLACE A DISTRICT</div><h3>${b.name}</h3><p>${b.description}</p><p>${state.faction==='kaiju'?'Grow outward from the castle heart. Add the outer ring for more plots. Upgrade districts to build higher.':'Choose an empty plot below or on your city.'}</p>${districtGrid()}`;}
 else if(selection?.slot!==undefined){
  const slot=selection.slot,b=state.buildings[slot],ring=state.faction==='kaiju'?` · ${['HEART','INNER WARD','OUTER WARD'][kaijuSlotPosition(slot).ring]}`:'';
  if(b){const cost=upgradeCost(b);html=`<div class="eyebrow">DISTRICT ${slot+1}${ring} · LEVEL ${b.level}</div><h3>${b.type==='cannon'&&state.faction==='airship'?'Missile battery':BUILDINGS[b.type].name}</h3><p>${BUILDINGS[b.type].description}</p>${b.remaining>0?`<div class="stats-row"><span>${b.upgrading?'Upgrading':'Building'}</span><strong>${Math.ceil(b.remaining)}s</strong></div>`:b.level<3?`<button class="primary" data-upgrade="${slot}" ${state.resources.wood<cost.wood||state.resources.iron<cost.iron?'disabled':''}>Upgrade · ${cost.wood} wood / ${cost.iron} iron</button>`:'<p>Maximum district level reached.</p>'}${b.type==='cannon'?batteryControls(slot,b):''}`;}
  else html=`<div class="eyebrow">DISTRICT ${slot+1}${ring}</div><h3>Room to grow.</h3><p>Choose a building from the construction bar to give this plot a purpose.</p>`;
 }else if(selection?.node){const n=state.nodes.find(n=>n.id===selection.node);html=`<div class="eyebrow">RESOURCE DEPOSIT · ${n.kind}</div><h3>${esc(n.name)}</h3><p>${Math.floor(n.amount)} ${n.kind} remains. Crews gather automatically when your city stops within 23 metres. Resource sites are protected from crushing.</p><div class="stats-row"><span>Distance</span><strong>${Math.ceil(distance(state,n))} m</strong></div><button class="primary" data-travel="${n.id}" ${n.amount<=0?'disabled':''}>Set course ↗</button>`;}
 else if(selection?.enemy){const e=state.enemies.find(e=>e.id===selection.enemy),d=distance(state,e);html=`<div class="eyebrow">RIVAL · ${FACTIONS[e.faction].type}</div><h3>${esc(e.name)}</h3><p>${e.defeated?'This rival has been defeated.':e.faction==='kaiju'?'A close-range predator. Keep away from its fists.':e.faction==='airship'?'Fast missile platforms. Close the distance before they can kite away.':'Heavy armour and mid-range guns. Prepare for a siege.'}</p><div class="stats-row"><span>Distance</span><strong>${Math.ceil(d)} m</strong></div>${e.defeated?'':d>42?`<button class="primary" data-approach="${e.id}">Approach city ↗</button>`:`<button class="primary" data-engage="${e.id}">Engage in battle ⚔</button>`}`;}
 if(html!==uiSignature){$('selection').innerHTML=html;uiSignature=html;}
}
function renderUI(){if(!started)return;const s=state,f=FACTIONS[s.faction],battle=s.mode==='battle';document.body.classList.toggle('in-battle',battle);document.body.classList.toggle('in-streets',view==='people'&&!battle);document.body.classList.toggle('in-carrier',view==='carrier'&&!battle);$('battle-hud').classList.toggle('hidden',!battle);$('city-type').textContent=f.type.toUpperCase();$('city-name').textContent=f.city;$('titan-view').classList.toggle('hidden',s.faction!=='kaiju');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 for(const k of ['wood','iron','food'])$(k).textContent=Math.floor(s.resources[k]);$('population').textContent=`${Math.floor(s.population)} / ${capacity(s)}`;const rate=income(s).food;$('food-rate').textContent=`${rate>=0?'+':''}${rate.toFixed(1)}/s`;$('food-rate').classList.toggle('negative',rate<0);$('hull-number').textContent=`${Math.ceil(s.hp)} / ${maxHull(s)}`;$('hull-bar').style.width=`${Math.max(0,s.hp/maxHull(s)*100)}%`;$('day').textContent=`DAY ${String(s.day).padStart(2,'0')}`;$('pause').textContent=s.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',s.paused?'Resume game':'Pause game');$('speed').textContent=`${s.speed}×`;$('paused-banner').classList.toggle('hidden',!s.paused||$('dialog').open);
 const node=s.nodes.find(n=>n.id===s.gathering);$('travel-status').textContent=battle?'⚔ Battle stations':s.starving?'⚠ Food depleted. Build gardens or find food.':node?`↟ Gathering ${node.kind} at ${node.name}`:s.target?`↗ On the move · ${Math.ceil(distance(s,s.target))} m to destination`:'◉ At anchor · Awaiting your orders';
 $('repair').disabled=battle||s.hp>=maxHull(s)||s.resources.wood<15||s.resources.iron<20;
 const ringButton=$('expand-ring');ringButton.classList.toggle('hidden',s.faction!=='kaiju');ringButton.disabled=battle||s.rings>=2||!!s.ringConstruction||s.resources.wood<90||s.resources.iron<65;
 ringButton.innerHTML=s.ringConstruction?`Building outer ring <span>${Math.ceil(s.ringConstruction.remaining)} seconds remaining</span>`:s.rings>=2?'Outer ring complete <span>20 district plots · Upgrade to build higher</span>':'Add outer ring <span>90 wood · 65 iron · 13 new plots</span>';
 const goals=[[s.stats.gathered>=75,'Gather 75 resources'],[s.stats.built>=2,'Build or upgrade 2 districts'],[s.stats.victories>=1,'Defeat your first rival']];$('objectives').innerHTML=goals.map(([done,text])=>`<div class="objective-item ${done?'done':''}"><i>${done?'✓':''}</i><span>${text}</span></div>`).join('');
 $('journal').replaceChildren(...s.log.slice(0,3).map(item=>{const p=document.createElement('p');p.textContent=item.text;return p;}));
 document.querySelectorAll('[data-building]').forEach(b=>{const kind=b.dataset.building,c=BUILDINGS[kind].cost;b.disabled=s.resources.wood<c.wood||s.resources.iron<c.iron||battle;b.classList.toggle('active',selectedBuilding===kind);});$('cancel-build').classList.toggle('hidden',!selectedBuilding);$('build-hint').textContent=selectedBuilding?`Place ${BUILDINGS[selectedBuilding].name} on an empty plot`:'Choose a building, then an empty district';
 if(!battle)renderSelection();else{const b=s.battle,d=distance(b.player,b.enemy);$('enemy-name').textContent=b.enemyName;$('enemy-type').textContent=FACTIONS[b.enemyFaction].type.toUpperCase();$('enemy-hp').textContent=`${Math.ceil(b.enemyHp)} / ${Math.ceil(b.enemyMaxHp)}`;$('enemy-bar').style.width=`${Math.max(0,b.enemyHp/b.enemyMaxHp*100)}%`;$('battle-distance').textContent=`${Math.ceil(d)} m apart · Your weapon range: ${f.range} m`;$('fire').disabled=b.reload>0||d>f.range||!!b.result||s.paused;$('fire').innerHTML=b.reload>0?`Reloading · ${b.reload.toFixed(1)}s`:`${weaponStatus(s).melee?'Melee strike':'Fire battery'} <kbd>Space</kbd>`;$('ability').disabled=b.abilityCooldown>0||!!b.result||s.paused;$('ability').textContent=b.abilityCooldown>0?`${f.ability} · ${Math.ceil(b.abilityCooldown)}s`:`${f.ability} [E]`;$('ability').title=f.abilityHint;$('autofire').textContent=`Auto-fire: ${b.autoFire?'on':'off'}`;document.querySelectorAll('[data-command]').forEach(el=>el.classList.toggle('active',el.dataset.command===b.command));$('battle-advice').textContent=s.faction==='kaiju'?'Close to 70 m, then use Titan rush. Close until your fists can reach the rival hull.':s.faction==='airship'?'Keep distance and use your 112 m missile range. Avoid close combat.':'Approach to cannon range. Use Siege ram to finish at close quarters.';if(b.result)showResult();}
 if(battle){const weapons=weaponStatus(s),b=s.battle;$('fire').disabled=b.reload>0||!weapons.canFire||!!b.result||s.paused;const blocked=weapons.batteries.filter(w=>w.blocker!==null).length;$('battery-status').textContent=weapons.melee?'Close combat · Fists / ram engage':`${weapons.active} / ${weapons.total} batteries bearing on target${blocked?` · ${blocked} blocked by your buildings`:''}`;}
 drawMap();
}
function drawMap(){const ctx=mapContext,w=230,h=190;ctx.clearRect(0,0,w,h);ctx.fillStyle='#293f32';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#b7bea01a';ctx.lineWidth=1;for(let x=0;x<w;x+=23){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=19){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}const p=o=>[(o.x+180)/360*w,(o.z+180)/360*h];ctx.lineWidth=4;ctx.strokeStyle='#748c793d';ctx.beginPath();for(let i=-12;i<=12;i++){const [x,y]=p({x:riverX(i*20),z:i*20});i===-12?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();
 for(const n of state.nodes){const [x,y]=p(n);ctx.fillStyle=n.amount<=0?'#687b61':n.kind==='wood'?'#aac897':n.kind==='iron'?'#bfc5b3':'#e1c783';ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();}for(const e of state.enemies){if(e.defeated)continue;const [x,y]=p(e);ctx.fillStyle='#d8a18b';ctx.beginPath();ctx.moveTo(x,y-4);ctx.lineTo(x+4,y);ctx.lineTo(x,y+4);ctx.lineTo(x-4,y);ctx.fill();}const [x,y]=p(state);if(state.target){const [tx,ty]=p(state.target);ctx.setLineDash([3,3]);ctx.lineWidth=1;ctx.strokeStyle='#f5dfab';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(tx,ty);ctx.stroke();ctx.setLineDash([]);}ctx.save();ctx.translate(x,y);ctx.rotate(-state.angle);ctx.fillStyle='#ffebbb';ctx.beginPath();ctx.moveTo(0,6);ctx.lineTo(-4,-4);ctx.lineTo(4,-4);ctx.fill();ctx.restore();ctx.strokeStyle='#dfdfb850';ctx.beginPath();ctx.arc(x,y,11,0,Math.PI*2);ctx.stroke();}
function updateMarkers(){for(const e of markerEls){const obj=[...state.nodes,...state.enemies].find(n=>n.id===e.dataset.id);const visible=started&&view!=='carrier'&&view!=='people'&&state.mode!=='battle'&&!obj.defeated&&(view==='world'||distance(state,obj)<100);if(!visible){e.style.display='none';continue;}const p=scene.project(obj.x,terrainHeight(obj.x,obj.z)+(obj.faction?obj.faction==='kaiju'?33:obj.faction==='crawler'?26:35:15),obj.z);const w=innerWidth,h=innerHeight;const clear=p.x>(w<=540?175:285)&&p.x<w-(w<=540?155:250)&&p.y>155&&p.y<h-210;e.style.display=p.visible&&clear?'block':'none';e.style.left=`${p.x}px`;e.style.top=`${p.y}px`;}}
function inputVector(){const up=keys.has('w')||keys.has('arrowup')||touch.has('up'),down=keys.has('s')||keys.has('arrowdown')||touch.has('down'),left=keys.has('a')||keys.has('arrowleft')||touch.has('left'),right=keys.has('d')||keys.has('arrowright')||touch.has('right');const f=Number(up)-Number(down),r=Number(right)-Number(left),yaw=scene.yaw;return {x:Math.cos(yaw)*r-Math.sin(yaw)*f,z:-Math.sin(yaw)*r-Math.cos(yaw)*f};}
function frame(now){const dt=Math.min((now-previous)/1000,.08);previous=now;if(started){tick(state,dt,inputVector());uiElapsed+=dt;saveElapsed+=dt;if(uiElapsed>.16){renderUI();uiElapsed=0;}if(saveElapsed>30){save();saveElapsed=0;}const event=state.battle?.events.at(-1);if(event&&event.id>lastAudioEvent){lastAudioEvent=event.id;sound(event.kind==='impact'?65:150,.35);}}else state.time+=dt;
 scene.update(state,dt,selectedSlot);updateMarkers();requestAnimationFrame(frame);}
function setBuild(type){if(state.mode==='battle')return;selectedBuilding=type;selection=null;selectedSlot=null;changeView('city');uiSignature='';renderUI();}
function pauseToggle(){if($('dialog').open)return;state.paused=!state.paused;renderUI();}
$('begin').addEventListener('click',()=>{if(cachedSave){showDialog('<span class="eyebrow">NEW EXPEDITION</span><h2>Start a new journey?</h2><p>A saved expedition already exists. Beginning a new one will replace it when the game next saves.</p><button class="primary" data-dialog-action="restart">Begin new expedition</button><button class="text-button" data-dialog-action="close">Keep saved expedition</button>');}else beginGame();});
$('continue').addEventListener('click',()=>{let saved;try{saved=deserialize(localStorage.getItem(SAVE_KEY));}catch{}if(saved)beginGame(saved);else toast('No readable save was found. Start a new expedition.');});
document.querySelectorAll('[data-faction]').forEach(b=>b.addEventListener('click',()=>chooseFaction(b.dataset.faction)));
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>changeView(b.dataset.view)));
for(const [kind,b]of Object.entries(BUILDINGS)){if(kind==='keep')continue;const el=document.createElement('button');el.className='build-option';el.dataset.building=kind;el.title=b.description;el.setAttribute('aria-label',`Build ${b.name}, ${b.cost.wood} wood and ${b.cost.iron} iron`);el.innerHTML=`<span class="icon">${b.icon}</span><span class="name">${b.name}</span><span class="cost">${b.cost.wood} ♧ · ${b.cost.iron} ⬡</span>`;el.addEventListener('click',()=>setBuild(kind));$('buildings').append(el);}
$('selection').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.slot!==undefined){select({slot:Number(d.slot)});}if(d.upgrade!==undefined)actionResult(upgrade(state,Number(d.upgrade)));if(d.facing!==undefined)actionResult(setBatteryFacing(state,Number(d.aimSlot),Number(d.facing)));if(d.travel){const n=state.nodes.find(n=>n.id===d.travel);travelToResource(n);toast(`Course set for ${n.name}.`);}if(d.approach){const n=state.enemies.find(e=>e.id===d.approach);const dist=distance(state,n);travel(state,n.x+(state.x-n.x)/dist*32,n.z+(state.z-n.z)/dist*32);toast('Approaching rival city. Select Engage when you arrive.');}if(d.engage){if(startBattle(state,d.engage)){selectedSlot=null;selectedBuilding=null;resultShown=false;lastAudioEvent=0;toast('Battle stations. Choose your distance and use your special ability.');sound(75,.8);}}renderUI();});
$('cancel-build').addEventListener('click',()=>{selectedBuilding=null;uiSignature='';renderUI();});$('pause').addEventListener('click',pauseToggle);$('speed').addEventListener('click',()=>{state.speed=state.speed===1?2:1;renderUI();});$('repair').addEventListener('click',()=>actionResult(repair(state)));$('save').addEventListener('click',()=>save(true));$('help').addEventListener('click',showHelp);$('menu').addEventListener('click',menu);
$('destinations-toggle').addEventListener('click',()=>$('destinations').classList.toggle('hidden'));
$('expand-ring').addEventListener('click',()=>actionResult(expandRing(state)));
$('quality').addEventListener('click',()=>{const options=['high','balanced','performance'];const q=options[(options.indexOf(scene.quality)+1)%options.length];scene.setQuality(q);$('quality').textContent=`Detail: ${q}`;toast(q==='high'?'High detail: full shadows and contact shading.':q==='balanced'?'Balanced detail: lighter shadows and shading.':'Performance mode: lower resolution and simplified shadows.');});
$('lighting').addEventListener('click',()=>{const options=['day','dusk','night'];const light=options[(options.indexOf(scene.light)+1)%options.length];scene.setLighting(light);$('lighting').textContent=`Light: ${light}`;});
$('sound').addEventListener('click',async()=>{audioEnabled=!audioEnabled;if(audioEnabled){audioContext ||= new (window.AudioContext||window.webkitAudioContext)();await audioContext.resume();sound(230,.4);}$('sound').textContent=`Sound: ${audioEnabled?'on':'off'}`;});
$('minimap').addEventListener('click',e=>{if(state.mode==='battle')return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*360-180,z=(e.clientY-r.top)/r.height*360-180;const nearby=[...state.nodes,...state.enemies.filter(e=>!e.defeated)].find(n=>Math.hypot(n.x-x,n.z-z)<16);if(nearby)select(nearby.faction?{enemy:nearby.id}:{node:nearby.id});else{travel(state,x,z);renderUI();}});
document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>{if(state.battle&&!state.battle.result)state.battle.command=b.dataset.command;renderUI();}));$('autofire').addEventListener('click',()=>{if(state.battle)state.battle.autoFire=!state.battle.autoFire;renderUI();});$('fire').addEventListener('click',()=>{fire(state);renderUI();});$('ability').addEventListener('click',()=>{const r=ability(state);if(!r.ok)toast(r.message);else sound(70,.7);renderUI();});
$('withdraw').addEventListener('click',()=>{if(!state.battle?.result){leaveBattle(state,true);resultShown=false;state.paused=false;renderUI();toast('The city has withdrawn. Repair before returning to battle.');}});
document.querySelectorAll('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch.add(b.dataset.move);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>touch.delete(b.dataset.move));});
window.addEventListener('keydown',e=>{if(!started||$('dialog').open||e.target.closest('button,input,select,textarea')&&e.key===' ')return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='1')changeView('city');if(k==='2')changeView('world');if(k==='3'&&state.faction==='kaiju')changeView('carrier');if(k==='4')changeView('people');if(k==='p')pauseToggle();if(k===' '&&state.mode==='battle'){fire(state);renderUI();}if(k==='e'&&state.mode==='battle'){const r=ability(state);if(!r.ok)toast(r.message);renderUI();}if(k==='escape'){selectedBuilding=null;selection=null;selectedSlot=null;renderUI();}});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();touch.clear();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started){state.paused=true;save();renderUI();}});window.addEventListener('beforeunload',()=>save());
try{scene=new GameScene($('world'),select);chooseFaction('kaiju');$('loading').classList.add('hidden');$('continue').classList.toggle('hidden',!cachedSave);requestAnimationFrame(frame);
 if(new URLSearchParams(location.search).has('test'))window.__colossus={get state(){return state;},get scene(){return scene;},advance(seconds){for(let t=0;t<seconds;t+=.1)tick(state,.1);renderUI();},snapshot(){return JSON.parse(serialize(state));}};
}catch(error){$('loading').classList.add('hidden');$('error').classList.remove('hidden');$('error').textContent=`The 3D renderer could not start. Open this game in an updated Chrome or Edge browser with hardware acceleration enabled. Details: ${error.message}`;console.error(error);}
