import {FACTIONS,BUILDINGS,SAVE_KEY,createGame,build,upgrade,upgradeCost,repair,travel,tick,distance,capacity,maxHull,income,startBattle,fire,ability,leaveBattle,serialize,deserialize,expandRing,slotUnlocked,setBatteryFacing,weaponStatus} from './simulation.js';
import {GameScene} from './scene.js';
import {createVerticalLayout,nextVerticalSlot} from './vertical-city.js';
import {CARRIER_VARIANTS,VARIANTS_BY_FACTION,normalizeVariant} from './variants.js';
import {facingOf,defaultFacing,batteryArc,normalizeAngle} from './weapon-layout.js';
import {terrainHeight,riverX} from './terrain.js';
import {GameAudio} from './audio.js';
import {createPlaytestTools} from './playtest.js';
import {selectionIntent} from './selection-intent.js';
import {createMarkerLayoutCache,placeMarker} from './marker-layout.js';

const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=createGame(),started=false,view='city',selectedSlot=null,selectedBuilding=null,selection=null,scene,keys=new Set(),touch=new Set(),previous=performance.now(),uiElapsed=0,saveElapsed=0,toastTimer,resultShown=false,priorPause=false,uiSignature='';
const audio=new GameAudio();
const compactTouch=()=>matchMedia('(pointer: coarse) and (max-width: 700px), (pointer: coarse) and (max-height: 560px)').matches;
const markerEls=[];const mapContext=$('minimap').getContext('2d');
const markerLayout=createMarkerLayoutCache({markers:()=>markerEls,occluders:()=>document.querySelectorAll('[data-marker-occlusion]')});
let cachedSave=null;try{cachedSave=deserialize(localStorage.getItem(SAVE_KEY));}catch{}
function setMobilePanel(panel=''){document.body.dataset.mobilePanel=panel;document.querySelectorAll('[data-mobile-panel]').forEach(b=>b.setAttribute('aria-expanded',String(b.dataset.mobilePanel===panel)));markerLayout.invalidate();}
function clearInput(){keys.clear();touch.clear();scene?.clearPointerInput?.();document.querySelectorAll('[data-move]').forEach(b=>{for(const id of b._heldPointers??[]){if(b.hasPointerCapture(id))b.releasePointerCapture(id);}b._heldPointers?.clear();});}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3800);}
function save(show=false){if(!started)return true;try{const raw=serialize(state);localStorage.setItem(SAVE_KEY,raw);cachedSave=deserialize(raw);if(show)toast('Expedition saved on this device.');return true;}catch{toast('Browser storage is unavailable. Export a save backup from Play on your devices.');return false;}}
function chooseFaction(faction,variant){
 if(!FACTIONS[faction])return;variant=normalizeVariant(faction,variant);state=createGame(faction,variant);audio.reset(state);scene.setGame(state,{preview:true});scene.setView('city');selectedSlot=null;
 document.querySelectorAll('[data-faction]').forEach(b=>b.classList.toggle('active',b.dataset.faction===faction));const f=FACTIONS[faction],v=CARRIER_VARIANTS[variant];
 $('faction-description').innerHTML=`<span class="eyebrow">${f.tag}</span><h2>${v.name}</h2><p>${v.description}</p>`;
 $('variant-options').innerHTML=VARIANTS_BY_FACTION[faction].map(id=>`<button data-variant="${id}" class="${id===variant?'active':''}" aria-pressed="${id===variant}"><span>${CARRIER_VARIANTS[id].label}</span><small>${id===variant?'Selected':'Preview this carrier'}</small></button>`).join('');
}
function markerSetup(){for(const el of markerEls)el.remove();markerEls.length=0;for(const n of [...state.nodes,...state.enemies]){const e=document.createElement('button');e.className='map-marker'+(n.faction?' rival':'');e.dataset.id=n.id;e.textContent=(n.faction?'◆ ':n.kind==='wood'?'♧ ':n.kind==='iron'?'⬡ ':'❧ ')+n.name;e.addEventListener('click',()=>select(n.faction?{enemy:n.id}:{node:n.id}));$('markers').append(e);markerEls.push(e);} $('destinations').replaceChildren();for(const n of state.nodes){const b=document.createElement('button');b.textContent=`${n.name} · ${n.kind}`;b.addEventListener('click',()=>{travelToResource(n);toast(`Course set for ${n.name}. Gathering starts on arrival.`);renderUI();});$('destinations').append(b);}markerLayout.invalidate({markers:true});}
function beginGame(saved=null){state=saved||createGame(state.faction,state.variant);state.paused=false;started=true;view='city';setMobilePanel();selection=null;selectedSlot=null;selectedBuilding=null;uiSignature='';resultShown=false;audio.reset(state);audio.setPaused(false);void audio.unlock().then(()=>audio.play('confirm')).catch(()=>toast('Sound could not start. Use Sound to try again.'));scene.setGame(state);scene.setView(view);$('intro').classList.add('hidden');$('faction-select').classList.add('hidden');$('hud').classList.remove('hidden');$('markers').classList.remove('hidden');markerSetup();renderUI();if(!saved)toast('Your expedition begins. Travel to the grove, or build your first district.');audioLabels();}
function changeView(v){if(state.mode==='battle'||v==='carrier'&&state.faction!=='kaiju')return;view=v;scene.setView(v);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderUI();}
function travelToResource(node){audio.play('travel');const d=distance(state,node);const dx=d>.01?(state.x-node.x)/d:0,dz=d>.01?(state.z-node.z)/d:1;travel(state,node.x+dx*22,node.z+dz*22);}
function actionResult(r){if(!r.ok)toast(r.message);else{audio.play('confirm');selectedBuilding=null;uiSignature='';renderUI();}return r.ok;}
function select(hit){const intent=selectionIntent(hit,{started,dialogOpen:$('dialog').open,mode:state.mode,placingBuilding:!!selectedBuilding});if(intent.kind==='ignore')return;if(compactTouch()&&intent.opensContext)setMobilePanel('city');
 if(hit.slot!==undefined){selectedSlot=hit.slot;selection={slot:hit.slot};if(selectedBuilding){actionResult(build(state,selectedBuilding,hit.slot));scene.update(state,0,selectedSlot);}if(state.faction==='kaiju')scene.setTowerFloor(scene.city.slotPositions[hit.slot].tier);renderUI();}
 else if(hit.node){selection={node:hit.node};selectedSlot=null;selectedBuilding=null;renderUI();}
 else if(hit.enemy){selection={enemy:hit.enemy};selectedSlot=null;selectedBuilding=null;renderUI();}
 else if(hit.ground){if(selectedBuilding){toast(state.faction==='kaiju'?'Use Add above castle to place the next storey.':'Choose an empty district on the city deck, or use the district grid.');return;}travel(state,hit.ground.x,hit.ground.z);if(compactTouch())setMobilePanel();selection=null;selectedSlot=null;audio.play('travel');renderUI();}}
function showDialog(html){if(!$('dialog').open)priorPause=state.paused;state.paused=true;audio.setPaused(true);clearInput();$('dialog-content').innerHTML=html;$('close-dialog').classList.toggle('hidden',resultShown&&!!state.battle?.result);if(!$('dialog').open)$('dialog').showModal();$('dialog').scrollTop=0;renderUI();}
function closeDialog(){if($('dialog').open)$('dialog').close();}
$('dialog').addEventListener('close',()=>{if($('dialog').open)return;if(!resultShown)state.paused=priorPause;audio.setPaused(!started||state.paused);renderUI();});
$('dialog').addEventListener('cancel',e=>{if(resultShown&&state.battle?.result)e.preventDefault();});
$('close-dialog').addEventListener('click',()=>{if(!resultShown||!state.battle?.result)closeDialog();});
function showHelp(){showDialog(`<span class="eyebrow">FIELD MANUAL</span><h2>Make a moving home.</h2><p>Begin by building a Timber guild. Travel to the Sunken Grove using the world map or Resource destinations. Your crews gather automatically when your city stops nearby.</p><div class="help-grid"><b>W A S D / Arrows</b><span>Move your city in the camera’s direction.</span><b>Drag / Scroll or pinch</b><span>Orbit the camera / zoom in and out. On touch screens, use the arrow pad to move.</span><b>1 / 2 / 3 / 4</b><span>City / world / titan / streets. Streets brings you close to the people.</span><b>Castle levels</b><span>Each Gothic district adds a storey on top. Upgrades make its storey taller and lift everything above it. Reinforce the harness for capacity beyond seven storeys.</span><b>Weapon placement</b><span>Select a battery to set its firing direction. Keep cannon lines clear of your buildings.</span><b>Build a district</b><span>Gothic cities: choose a building, then Add above castle. Other cities: choose an empty deck plot.</span><b>Upgrade</b><span>Select an existing building. Districts have three upgrade levels. Gothic upgrades raise the castle.</span><b>Battle</b><span>Move within 42 metres of a rival, select it, and engage. Use Approach or Keep distance. Guns fire automatically in range.</span><b>Space / E</b><span>Fire weapons / use your city’s special ability.</span><b>P</b><span>Pause. Building orders also work while paused.</span></div><p>Food feeds your population. Gardens produce food; woodland and ruins provide wood and iron. Falling to zero food slowly reduces population. Defeat every rival to secure the region. No rival attacks until you engage.</p><p>Progress autosaves every 30 seconds, plus when the game is hidden or closed. Sound is optional. Everything runs on this device.</p><button class="primary" data-dialog-action="close">Back to the expedition</button>`);}
function menu(){showDialog(`<span class="eyebrow">EXPEDITION PAUSED</span><h2>A moment at anchor.</h2><p>Your city is safe while this menu is open.</p><div class="menu-buttons"><button class="primary" data-dialog-action="close">Resume expedition</button><button data-dialog-action="save">Save on this device</button><button data-dialog-action="playtest">Playtest, offline & save transfer</button></div><section class="menu-settings"><h3>Presentation</h3><p>Compare the existing presets on your device.</p><div class="settings-grid"><button data-setting="quality">Detail: ${scene.quality}</button><button data-setting="lighting">Light: ${scene.light}</button><button data-setting="camera-motion">Camera: ${scene.cinematic.mode}</button><button data-setting="sound">Sound: ${audio.getSettings().muted?'off':'on'}</button><button data-setting="audio-settings">Audio mix</button><button data-setting="speed">Game speed: ${state.speed}×</button></div></section><div class="menu-buttons"><button data-dialog-action="help">Controls & help</button><button data-dialog-action="title">Save & return to title</button></div>`);}

function returnToTitle(){if(!save())return;closeDialog();started=false;state=createGame(state.faction,state.variant);$('hud').classList.add('hidden');$('intro').classList.remove('hidden');$('faction-select').classList.remove('hidden');$('markers').classList.add('hidden');$('continue').classList.remove('hidden');document.body.classList.remove('in-battle');chooseFaction(state.faction,state.variant);}
$('dialog-content').addEventListener('click',e=>{const setting=e.target.closest('[data-setting]')?.dataset.setting;if(setting){$(setting).click();if(setting!=='audio-settings')menu();return;}const a=e.target.closest('[data-dialog-action]')?.dataset.dialogAction;if(!a)return;if(a==='close')closeDialog();if(a==='save')save(true);if(a==='help')showHelp();if(a==='playtest')playtest.open();if(a==='title')returnToTitle();if(a==='return'){leaveBattle(state);state.paused=false;priorPause=false;resultShown=false;closeDialog();uiSignature='';renderUI();save();}if(a==='restart'){priorPause=false;closeDialog();beginGame();}});
function showResult(){const b=state.battle;if(!b?.result||resultShown||state.time-(b.finishedAt??-Infinity)<.65)return;resultShown=true;const victory=b.result==='victory',complete=state.enemies.every(e=>e.defeated);showDialog(`<span class="eyebrow">${complete?'THE ASHEN REACH IS YOURS':victory?'BATTLE WON':'EXPEDITION LOST'}</span><h2>${complete?'A future worth carrying.':victory?'The city still stands.':'Even giants can fall.'}</h2><p>${complete?'Every rival city has fallen. Your people have a place in this world. Keep building and exploring, or begin again with a different city.':victory?`You defeated ${esc(b.enemyName)}. Salvage crews are bringing supplies aboard. Repair your hull before the next engagement.`:'Your city was overwhelmed. Try building gun batteries and bulwarks, repair before battle, and fight at the distance that suits your city.'}</p>${victory?'<div class="result-loot"><span>+95 wood</span><span>+100 iron</span><span>+65 food</span></div>':''}<button class="primary" data-dialog-action="${victory?'return':'restart'}">${victory?'Return to the expedition':'Begin a new expedition'}</button>${!victory?'<button class="text-button" data-dialog-action="title">Return to city selection</button>':''}`);audio.play(victory?'victory':'defeat',{allowPaused:true});save();}
function districtGrid(){
 if(state.faction==='kaiju'){
  const layout=createVerticalLayout(state.buildings,state.towerOrder,state.variant),next=nextVerticalSlot(state.buildings,state.rings);
  return `<div class="vertical-build"><div class="stack-direction">↑ BUILDS UPWARD</div>${next!==null?`<button class="primary" data-slot="${next}">Add above castle · Storey ${layout.floors.length+1}</button>`:`<p>${layout.floors.length>=20?'The castle has reached its 20-storey capacity. Upgrade existing districts to build higher.':'Reinforce the harness to support more storeys.'}</p>`}<div class="stack-preview">${layout.floors.slice(-3).reverse().map(f=>`<span>Storey ${f.tier+1} · ${BUILDINGS[f.type].name}</span>`).join('')}</div><small>One district per storey. The footprint stays the same.</small></div>`;
 }
 return `<div class="district-grid">${state.buildings.map((b,i)=>`<button data-slot="${i}" class="${b?'occupied':''}" ${b?'disabled':''} title="District ${i+1}${b?' · Occupied':''}">${i+1}</button>`).join('')}</div>`;
}
function batteryControls(slot,b){
 const facing=facingOf(state.faction,slot,b),arc=Math.round(batteryArc(state.faction)*180/Math.PI);
 return `<div class="battery-placement"><div class="eyebrow">WEAPON DIRECTION · ${arc}° ARC</div><p>${state.faction==='airship'?'Missiles clear your buildings and turn through a wide arc.':state.faction==='kaiju'?"Face outward aligns with this storey's rear portal. Masonry and the kaiju can block other angles.":'Cannon fire needs a clear line past your other buildings. Outer positions offer better coverage.'}</p><div class="bearing-controls">${[['Fore',0],['Starboard',Math.PI/2],['Aft',Math.PI],['Port',-Math.PI/2],['Face outward',defaultFacing(state.faction,slot)]].map(([label,a])=>`<button data-facing="${a}" data-aim-slot="${slot}" class="${Math.abs(normalizeAngle(facing-a))<.01?'active':''}">${label}</button>`).join('')}</div><small>Gold outline: firing arc · ${FACTIONS[state.faction].range} m range</small></div>`;
}
function renderSelection(){
 let html='';
 if(selectedBuilding){const b=BUILDINGS[selectedBuilding];html=`<div class="eyebrow">${state.faction==='kaiju'?'ADD A STOREY':'PLACE A DISTRICT'}</div><h3>${b.name}</h3><p>${b.description}</p><p>${state.faction==='kaiju'?'This district goes directly above the current top of your castle.':'Choose an empty plot below or on your city.'}</p>${districtGrid()}`;}
 else if(selection?.slot!==undefined){
  const slot=selection.slot,b=state.buildings[slot],ring=state.faction==='kaiju'?` · STOREY ${createVerticalLayout(state.buildings,state.towerOrder,state.variant).positions[slot].tier+1}`:'';
  if(b){const cost=upgradeCost(b);html=`<div class="eyebrow">DISTRICT ${slot+1}${ring} · UPGRADE ${b.level}</div><h3>${b.type==='cannon'&&state.faction==='airship'?'Missile battery':BUILDINGS[b.type].name}</h3><p>${BUILDINGS[b.type].description}</p>${state.faction==='kaiju'&&b.level<3?`<p>${b.upgrading?'A taller section is under construction. The storeys above have been raised.':b.remaining>0?'Masons are raising this new storey above the castle.':'Upgrading makes this storey taller and raises every storey above it.'}</p>`:''}${b.remaining>0?`<div class="stats-row"><span>${b.upgrading?'Upgrading':'Building'}</span><strong>${Math.ceil(b.remaining)}s</strong></div>`:b.level<3?`<button class="primary" data-upgrade="${slot}" ${state.resources.wood<cost.wood||state.resources.iron<cost.iron?'disabled':''}>Upgrade · ${cost.wood} wood / ${cost.iron} iron</button>`:'<p>Maximum district level reached.</p>'}${b.type==='cannon'?batteryControls(slot,b):''}`;}
  else html=`<div class="eyebrow">DISTRICT ${slot+1}${ring}</div><h3>Room to grow.</h3><p>Choose a building from the construction bar to give this plot a purpose.</p>`;
 }else if(selection?.node){const n=state.nodes.find(n=>n.id===selection.node);html=`<div class="eyebrow">RESOURCE DEPOSIT · ${n.kind}</div><h3>${esc(n.name)}</h3><button class="primary" data-travel="${n.id}" ${n.amount<=0?'disabled':''}>Set course ↗</button><div class="stats-row"><span>Distance</span><strong>${Math.ceil(distance(state,n))} m</strong></div><p>${Math.floor(n.amount)} ${n.kind} remains. Crews gather automatically when your city stops within 23 metres. Resource sites are protected from crushing.</p>`;}
 else if(selection?.enemy){const e=state.enemies.find(e=>e.id===selection.enemy),d=distance(state,e);html=`<div class="eyebrow">RIVAL · ${CARRIER_VARIANTS[e.variant]?.label??FACTIONS[e.faction].type}</div><h3>${esc(e.name)}</h3>${e.defeated?'':d>42?`<button class="primary" data-approach="${e.id}">Approach city ↗</button>`:`<button class="primary" data-engage="${e.id}">Engage in battle ⚔</button>`}<div class="stats-row"><span>Distance</span><strong>${Math.ceil(d)} m</strong></div><p>${e.defeated?'This rival has been defeated.':e.faction==='kaiju'?'A close-range predator. Keep away from its fists.':e.faction==='airship'?'Fast missile platforms. Close the distance before they can kite away.':'Heavy armour and mid-range guns. Prepare for a siege.'}</p>`;}
 if(html!==uiSignature){$('selection').innerHTML=html;uiSignature=html;}
}
function renderUI(){if(!started)return;const s=state,f=FACTIONS[s.faction],battle=s.mode==='battle';document.body.classList.toggle('in-battle',battle);document.body.classList.toggle('in-streets',view==='people'&&!battle);document.body.classList.toggle('in-carrier',view==='carrier'&&!battle);$('battle-hud').classList.toggle('hidden',!battle);$('city-type').textContent=(CARRIER_VARIANTS[s.variant]?.label??f.type).toUpperCase();$('city-name').textContent=f.city;$('titan-view').classList.toggle('hidden',s.faction!=='kaiju');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 for(const k of ['wood','iron','food'])$(k).textContent=Math.floor(s.resources[k]);$('population').textContent=`${Math.floor(s.population)} / ${capacity(s)}`;const rate=income(s).food;$('food-rate').textContent=`${rate>=0?'+':''}${rate.toFixed(1)}/s`;$('food-rate').classList.toggle('negative',rate<0);$('city-population').textContent=$('population').textContent;$('city-food-rate').textContent=$('food-rate').textContent;$('city-food-rate').classList.toggle('negative',rate<0);$('hull-number').textContent=`${Math.ceil(s.hp)} / ${maxHull(s)}`;$('battle-own-hull').textContent=$('hull-number').textContent;$('hull-bar').style.width=`${Math.max(0,s.hp/maxHull(s)*100)}%`;$('day').textContent=`DAY ${String(s.day).padStart(2,'0')}`;$('pause').textContent=s.paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',s.paused?'Resume game':'Pause game');$('speed').textContent=`${s.speed}×`;$('paused-banner').classList.toggle('hidden',!s.paused||$('dialog').open);
 const node=s.nodes.find(n=>n.id===s.gathering);$('travel-status').textContent=battle?'⚔ Battle stations':s.starving?'⚠ Food depleted. Build gardens or find food.':node?`↟ Gathering ${node.kind} at ${node.name}`:s.target?`↗ On the move · ${Math.ceil(distance(s,s.target))} m to destination`:'◉ At anchor · Awaiting your orders';
 $('repair').disabled=battle||s.hp>=maxHull(s)||s.resources.wood<15||s.resources.iron<20;
 const ringButton=$('expand-ring');ringButton.classList.toggle('hidden',s.faction!=='kaiju');ringButton.disabled=battle||s.rings>=2||!!s.ringConstruction||s.resources.wood<90||s.resources.iron<65;
 ringButton.innerHTML=s.ringConstruction?`Reinforcing harness <span>${Math.ceil(s.ringConstruction.remaining)} seconds remaining</span>`:s.rings>=2?'Harness reinforced <span>Capacity: 20 stacked storeys</span>':'Reinforce castle harness <span>90 wood · 65 iron · Capacity: 7 → 20 storeys</span>';
 const floorControl=$('tower-floor-control');floorControl.classList.toggle('hidden',s.faction!=='kaiju'||battle);
 if(s.faction==='kaiju'){const layout=createVerticalLayout(s.buildings,s.towerOrder,s.variant),options=layout.floors.map(f=>`<option value="${f.tier}">Storey ${f.tier+1} · ${BUILDINGS[f.type].name}${f.underConstruction?' · Building':''}</option>`).join('');if($('tower-floor').dataset.signature!==options){$('tower-floor').innerHTML=options;$('tower-floor').dataset.signature=options;}$('tower-floor').value=String(scene.towerTier??0);}
 const goals=[[s.stats.gathered>=75,'Gather 75 resources'],[s.stats.built>=2,'Build or upgrade 2 districts'],[s.stats.victories>=1,'Defeat your first rival']];$('objectives').innerHTML=goals.map(([done,text])=>`<div class="objective-item ${done?'done':''}"><i>${done?'✓':''}</i><span>${text}</span></div>`).join('');
 $('journal').replaceChildren(...s.log.slice(0,3).map(item=>{const p=document.createElement('p');p.textContent=item.text;return p;}));
 document.querySelectorAll('[data-building]').forEach(b=>{const kind=b.dataset.building,c=BUILDINGS[kind].cost;b.disabled=s.resources.wood<c.wood||s.resources.iron<c.iron||battle;b.classList.toggle('active',selectedBuilding===kind);});$('cancel-build').classList.toggle('hidden',!selectedBuilding);$('build-hint').textContent=s.faction==='kaiju'?(selectedBuilding?'Add this district above the castle':'Each new district adds a storey above'):(selectedBuilding?`Place ${BUILDINGS[selectedBuilding].name} on an empty plot`:'Choose a building, then an empty district');
 if(!battle)renderSelection();else{const b=s.battle,d=distance(b.player,b.enemy),airborneDrill=s.variant==='drill'&&b.enemyFaction==='airship',abilityLabel=airborneDrill?'Siege burst':f.ability;$('enemy-name').textContent=b.enemyName;$('enemy-type').textContent=(CARRIER_VARIANTS[b.enemyVariant]?.label??FACTIONS[b.enemyFaction].type).toUpperCase();$('enemy-hp').textContent=`${Math.ceil(b.enemyHp)} / ${Math.ceil(b.enemyMaxHp)}`;$('enemy-bar').style.width=`${Math.max(0,b.enemyHp/b.enemyMaxHp*100)}%`;$('battle-distance').textContent=`${Math.ceil(d)} m apart · Your weapon range: ${f.range} m`;$('fire').disabled=b.reload>0||d>f.range||!!b.result||s.paused;$('fire').innerHTML=b.reload>0?`Reloading · ${b.reload.toFixed(1)}s`:`${weaponStatus(s).melee?'Melee strike':'Fire battery'} <kbd>Space</kbd>`;$('ability').disabled=b.abilityCooldown>0||!!b.result||s.paused;$('ability').innerHTML=b.abilityCooldown>0?`${esc(abilityLabel)} · ${Math.ceil(b.abilityCooldown)}s`:`${esc(abilityLabel)} <kbd>E</kbd>`;$('ability').title=f.abilityHint;$('autofire').textContent=`Auto-fire: ${b.autoFire?'on':'off'}`;document.querySelectorAll('[data-command]').forEach(el=>el.classList.toggle('active',el.dataset.command===b.command));$('battle-advice').textContent=s.faction==='kaiju'?'Close to 70 m, then use Titan rush. Close until your fists can reach the rival hull.':s.faction==='airship'?'Keep distance and use your 112 m missile range. Avoid close combat.':airborneDrill?'Use cannons and Siege burst against airborne cities. The drill engages ground hulls.':'Approach to cannon range. Use Siege ram to finish at close quarters.';if(b.result)showResult();}
 if(battle){const weapons=weaponStatus(s),b=s.battle;$('fire').disabled=b.reload>0||!weapons.canFire||!!b.result||s.paused;const blocked=weapons.batteries.filter(w=>w.blocker!==null).length;$('battery-status').textContent=weapons.melee?'Close combat · Fists / ram engage':`${weapons.active} / ${weapons.total} batteries bearing on target${blocked?` · ${blocked} blocked by city structures`:''}`;}
 if(battle&&s.variant==='drill'&&s.battle.enemyFaction==='airship')$('ability').title='Fire a 60-damage cannon burst at an airborne city.';
 drawMap();
}
function drawMap(){const ctx=mapContext,w=230,h=190;ctx.clearRect(0,0,w,h);ctx.fillStyle='#293f32';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#b7bea01a';ctx.lineWidth=1;for(let x=0;x<w;x+=23){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=19){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}const p=o=>[(o.x+180)/360*w,(o.z+180)/360*h];ctx.lineWidth=4;ctx.strokeStyle='#748c793d';ctx.beginPath();for(let i=-12;i<=12;i++){const [x,y]=p({x:riverX(i*20),z:i*20});i===-12?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();
 for(const n of state.nodes){const [x,y]=p(n);ctx.fillStyle=n.amount<=0?'#687b61':n.kind==='wood'?'#aac897':n.kind==='iron'?'#bfc5b3':'#e1c783';ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();}for(const e of state.enemies){if(e.defeated)continue;const [x,y]=p(e);ctx.fillStyle='#d8a18b';ctx.beginPath();ctx.moveTo(x,y-4);ctx.lineTo(x+4,y);ctx.lineTo(x,y+4);ctx.lineTo(x-4,y);ctx.fill();}const [x,y]=p(state);if(state.target){const [tx,ty]=p(state.target);ctx.setLineDash([3,3]);ctx.lineWidth=1;ctx.strokeStyle='#f5dfab';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(tx,ty);ctx.stroke();ctx.setLineDash([]);}ctx.save();ctx.translate(x,y);ctx.rotate(-state.angle);ctx.fillStyle='#ffebbb';ctx.beginPath();ctx.moveTo(0,6);ctx.lineTo(-4,-4);ctx.lineTo(4,-4);ctx.fill();ctx.restore();ctx.strokeStyle='#dfdfb850';ctx.beginPath();ctx.arc(x,y,11,0,Math.PI*2);ctx.stroke();}
function updateMarkers(){const layout=markerLayout.read(),occupied=[],objects=[...state.nodes,...state.enemies];for(const e of markerEls){const obj=objects.find(n=>n.id===e.dataset.id);const visible=started&&!$('dialog').open&&view!=='carrier'&&view!=='people'&&state.mode!=='battle'&&!obj.defeated&&(view==='world'||distance(state,obj)<100);if(!visible){e.style.display='none';continue;}const p=scene.project(obj.x,terrainHeight(obj.x,obj.z)+(obj.faction?obj.faction==='kaiju'?33:obj.faction==='crawler'?26:35:15),obj.z),size=layout.sizes.get(e),placed=size&&placeMarker({...p,...size},layout,occupied);e.style.display=placed?'block':'none';if(placed){e.style.left=placed.x+'px';e.style.top=placed.y+'px';occupied.push(placed.rect);}}}

function inputVector(){const up=keys.has('w')||keys.has('arrowup')||touch.has('up'),down=keys.has('s')||keys.has('arrowdown')||touch.has('down'),left=keys.has('a')||keys.has('arrowleft')||touch.has('left'),right=keys.has('d')||keys.has('arrowright')||touch.has('right');const f=Number(up)-Number(down),r=Number(right)-Number(left),yaw=scene.yaw;return {x:Math.cos(yaw)*r-Math.sin(yaw)*f,z:-Math.sin(yaw)*r-Math.cos(yaw)*f};}
function frame(now){const dt=Math.min((now-previous)/1000,.08);previous=now;if(started){const priorHp=state.hp,priorEnemyHp=state.battle?.enemyHp;tick(state,dt,inputVector());uiElapsed+=dt;saveElapsed+=dt;if(uiElapsed>.16||state.hp!==priorHp||state.battle?.enemyHp!==priorEnemyHp){renderUI();uiElapsed=0;}if(saveElapsed>30){save();saveElapsed=0;}}else state.time+=dt;
 scene.update(state,dt,selectedSlot);if(started)audio.update(state,scene);updateMarkers();playtest.frame(now);requestAnimationFrame(frame);}
function setBuild(type){if(state.mode==='battle')return;if(compactTouch())setMobilePanel('city');selectedBuilding=type;selection=null;selectedSlot=null;changeView('city');uiSignature='';renderUI();}
function pauseToggle(){if($('dialog').open)return;state.paused=!state.paused;audio.setPaused(state.paused);renderUI();}
$('begin').addEventListener('click',()=>{if(cachedSave){showDialog('<span class="eyebrow">NEW EXPEDITION</span><h2>Start a new journey?</h2><p>A saved expedition already exists. Beginning a new one will replace it when the game next saves.</p><button class="primary" data-dialog-action="restart">Begin new expedition</button><button class="text-button" data-dialog-action="close">Keep saved expedition</button>');}else beginGame();});
$('continue').addEventListener('click',()=>{let saved;try{saved=deserialize(localStorage.getItem(SAVE_KEY));}catch{}if(saved)beginGame(saved);else toast('No readable save was found. Start a new expedition.');});
document.querySelectorAll('[data-faction]').forEach(b=>b.addEventListener('click',()=>chooseFaction(b.dataset.faction)));
$('variant-options').addEventListener('click',e=>{const id=e.target.closest('[data-variant]')?.dataset.variant;if(id)chooseFaction(state.faction,id);});
$('tower-floor').addEventListener('change',()=>{const tier=Number($('tower-floor').value),floor=createVerticalLayout(state.buildings,state.towerOrder,state.variant).floors[tier];selectedBuilding=null;selectedSlot=floor?.slot??null;selection=selectedSlot===null?null:{slot:selectedSlot};scene.setTowerFloor(tier);changeView('people');});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>changeView(b.dataset.view)));
for(const [kind,b]of Object.entries(BUILDINGS)){if(kind==='keep')continue;const el=document.createElement('button');el.className='build-option';el.dataset.building=kind;el.title=b.description;el.setAttribute('aria-label',`Build ${b.name}, ${b.cost.wood} wood and ${b.cost.iron} iron`);el.innerHTML=`<span class="icon">${b.icon}</span><span class="name">${b.name}</span><span class="cost">${b.cost.wood} ♧ · ${b.cost.iron} ⬡</span>`;el.addEventListener('click',()=>setBuild(kind));$('buildings').append(el);}
$('selection').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.slot!==undefined){select({slot:Number(d.slot)});}if(d.upgrade!==undefined)actionResult(upgrade(state,Number(d.upgrade)));if(d.facing!==undefined)actionResult(setBatteryFacing(state,Number(d.aimSlot),Number(d.facing)));if(d.travel){const n=state.nodes.find(n=>n.id===d.travel);travelToResource(n);toast(`Course set for ${n.name}.`);}if(d.approach){const n=state.enemies.find(e=>e.id===d.approach);const dist=distance(state,n);travel(state,n.x+(state.x-n.x)/dist*32,n.z+(state.z-n.z)/dist*32);toast('Approaching rival city. Select Engage when you arrive.');}if(d.engage){if(startBattle(state,d.engage)){selectedSlot=null;selectedBuilding=null;resultShown=false;toast('Battle stations. Choose your distance and use your special ability.');audio.play('confirm',{intensity:.75});}}renderUI();});
$('cancel-build').addEventListener('click',()=>{selectedBuilding=null;uiSignature='';renderUI();});$('pause').addEventListener('click',pauseToggle);$('speed').addEventListener('click',()=>{state.speed=state.speed===1?2:1;renderUI();});$('repair').addEventListener('click',()=>{if(actionResult(repair(state)))audio.play('repair');});$('save').addEventListener('click',()=>save(true));$('help').addEventListener('click',showHelp);$('menu').addEventListener('click',menu);
$('destinations-toggle').addEventListener('click',()=>$('destinations').classList.toggle('hidden'));
$('expand-ring').addEventListener('click',()=>actionResult(expandRing(state)));
$('quality').addEventListener('click',()=>{const options=['high','balanced','performance'];const q=options[(options.indexOf(scene.quality)+1)%options.length];scene.setQuality(q);$('quality').textContent=`Detail: ${q}`;toast(q==='high'?'High detail: full shadows and contact shading.':q==='balanced'?'Balanced detail: lighter shadows and shading.':'Performance mode: lower resolution and simplified shadows.');});
$('lighting').addEventListener('click',()=>{const options=['day','dusk','night'];const light=options[(options.indexOf(scene.light)+1)%options.length];scene.setLighting(light);$('lighting').textContent=`Light: ${light}`;});
function cameraLabel(){$('camera-motion').textContent=`Camera: ${scene.cinematic.mode}`;$('camera-motion').setAttribute('aria-pressed',String(scene.cinematic.mode==='cinematic'));}
$('camera-motion').addEventListener('click',()=>{scene.setCameraMode(scene.cinematic.mode==='cinematic'?'steady':'cinematic');try{localStorage.setItem('colossus-camera-mode',scene.cinematic.mode);}catch{}cameraLabel();});
function audioLabels(){const s=audio.getSettings();$('sound').textContent=`Sound: ${s.muted?'off':'on'}`;$('sound').setAttribute('aria-pressed',String(!s.muted));}
$('sound').addEventListener('click',async()=>{const muted=!audio.getSettings().muted;audio.setMuted(muted);if(!muted)try{await audio.unlock();}catch{toast('Sound could not start. Try again after resuming the game.');}audioLabels();});
function showAudio(){const s=audio.getSettings();showDialog(`<span class="eyebrow">SOUND & MUSIC</span><h2>The sound of a moving world.</h2><p>Set your mix. These levels are saved on this device.</p><div class="audio-mix">${[['master','Overall volume'],['music','Music'],['ambience','Wind, water & wildlife'],['effects','Carriers & battle']].map(([bus,label])=>`<label for="mix-${bus}">${label}<output id="mix-value-${bus}">${Math.round(s[bus]*100)}%</output><input id="mix-${bus}" data-audio-bus="${bus}" type="range" min="0" max="100" value="${Math.round(s[bus]*100)}" /></label>`).join('')}</div><p class="audio-note">Sound begins when you enter the game and pauses with your expedition. Original sound design runs locally.</p><details class="asset-credit"><summary>Art credits</summary><p>Surface scans: <a href="https://polyhaven.com" target="_blank" rel="noopener noreferrer">Poly Haven</a>, CC0. Powered by Poly Haven. Bundled locally; the game makes no remote requests.</p></details><button class="primary" data-dialog-action="close">Back to the expedition</button>`);}
$('audio-settings').addEventListener('click',showAudio);
$('dialog-content').addEventListener('input',e=>{const bus=e.target.dataset.audioBus;if(bus){audio.setVolume(bus,Number(e.target.value)/100);$('mix-value-'+bus).textContent=e.target.value+'%';}});
audioLabels();
$('minimap').addEventListener('click',e=>{if(state.mode==='battle')return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*360-180,z=(e.clientY-r.top)/r.height*360-180;const nearby=[...state.nodes,...state.enemies.filter(e=>!e.defeated)].find(n=>Math.hypot(n.x-x,n.z-z)<16);if(nearby)select(nearby.faction?{enemy:nearby.id}:{node:nearby.id});else{travel(state,x,z);renderUI();}});
document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>{if(state.battle&&!state.battle.result)state.battle.command=b.dataset.command;renderUI();}));$('autofire').addEventListener('click',()=>{if(state.battle)state.battle.autoFire=!state.battle.autoFire;renderUI();});$('fire').addEventListener('click',()=>{fire(state);renderUI();});$('ability').addEventListener('click',()=>{const r=ability(state);if(!r.ok)toast(r.message);renderUI();});
$('withdraw').addEventListener('click',()=>{if(!state.battle?.result){leaveBattle(state,true);resultShown=false;state.paused=false;renderUI();toast('The city has withdrawn. Repair before returning to battle.');}});
document.querySelectorAll('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);(b._heldPointers??=new Set()).add(e.pointerId);touch.add(b.dataset.move);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,e=>{b._heldPointers?.delete(e.pointerId);if(!b._heldPointers?.size)touch.delete(b.dataset.move);});});
window.addEventListener('keydown',e=>{if(!started||$('dialog').open||e.target.isContentEditable||e.target.closest('input,select,textarea')||e.target.closest('button')&&e.key===' ')return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='1')changeView('city');if(k==='2')changeView('world');if(k==='3'&&state.faction==='kaiju')changeView('carrier');if(k==='4')changeView('people');if(k==='p')pauseToggle();if(k===' '&&state.mode==='battle'){fire(state);renderUI();}if(k==='e'&&state.mode==='battle'){const r=ability(state);if(!r.ok)toast(r.message);renderUI();}if(k==='escape'){selectedBuilding=null;selection=null;selectedSlot=null;setMobilePanel();renderUI();}});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',clearInput);window.addEventListener('orientationchange',clearInput);document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(started){state.paused=true;save();renderUI();}}});window.addEventListener('beforeunload',()=>save());window.addEventListener('pagehide',()=>{clearInput();save();});
function loadTransferredGame(saved){const previousState=state,previousStarted=started,previousCached=cachedSave;try{beginGame(saved);cachedSave=saved;priorPause=false;}catch(error){state=previousState;started=previousStarted;cachedSave=previousCached;throw error;}}
const playtest=createPlaytestTools({showDialog,closeDialog,getGame:()=>started?state:cachedSave,loadGame:loadTransferredGame,save,getQuality:()=>scene?.quality??'performance',getPlayState:()=>({started,paused:state.paused}),getRenderInfo:()=>({width:scene?.renderer.domElement.width??0,height:scene?.renderer.domElement.height??0}),toast});
$('playtest-open').addEventListener('click',()=>playtest.open());
document.querySelectorAll('[data-mobile-panel]').forEach(button=>button.addEventListener('click',()=>{const panel=button.dataset.mobilePanel;setMobilePanel(document.body.dataset.mobilePanel===panel?'':panel);}));
$('mobile-menu').addEventListener('click',menu);document.querySelectorAll('[data-close-panel]').forEach(b=>b.addEventListener('click',()=>setMobilePanel()));
try{scene=new GameScene($('world'),select);try{const mode=localStorage.getItem('colossus-camera-mode');if(['steady','cinematic'].includes(mode))scene.setCameraMode(mode);}catch{}cameraLabel();$('quality').textContent='Detail: '+scene.quality;chooseFaction('kaiju');$('loading').classList.add('hidden');$('continue').classList.toggle('hidden',!cachedSave);requestAnimationFrame(frame);
 if(new URLSearchParams(location.search).has('test'))window.__colossus={get state(){return state;},get scene(){return scene;},get audio(){return audio;},advance(seconds){for(let t=0;t<seconds;t+=.1)tick(state,.1);renderUI();},refreshMarkers(){updateMarkers();},snapshot(){return JSON.parse(serialize(state));}};
}catch(error){$('loading').classList.add('hidden');$('error').classList.remove('hidden');$('error').textContent=`The 3D renderer could not start. Open this game in an updated Safari, Chrome or Edge browser with hardware acceleration enabled. Details: ${error.message}`;console.error(error);}
